# https://github.com/nicolas-van/easy-markdown-to-github-pages

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
theme: jekyll-theme-time-machine
title: Guide Soubiron
description: Les Pyrénées - du Pic d'Anie au Canigou en 40 excursions, par Pierre Soubiron
